Adds unit test for unit conversions
NOAA-EMC/emcpy pull request #4
Opened 2021-07-22 19:03 UTC by CoryMartin-NOAA

Will be the first test the repo runs in CI; also works as an example on how to convert units using emcpy

2021-07-22 21:24 UTC, aerorahul commented
ok. we need to add an action to trigger the test.

2021-07-22 21:25 UTC, aerorahul requested changes
change `emc` to `emcpy`

2021-07-22 21:25 UTC, aerorahul commented on tests/test_convert_units.py
> +import emc.calcs.units
`emc` everywhere should become `emcpy`

2021-07-26 13:25 UTC, CoryMartin-NOAA commented on tests/test_convert_units.py
> +import emc.calcs.units
Changed, please re-review

2021-07-26 13:51 UTC, aerorahul commented on tests/test_convert_units.py
> +import emcpy.calcs.units
may be call the script `test_units.py`.

2021-07-26 14:09 UTC, aerorahul approved these changes

2021-07-26 14:10 UTC, merged